[package]
name = "breezyshim"
version = "0.1.99"
edition = "2021"
license = "GPL-2.0+"
description = "Rust shim around the Breezy Python API"
homepage = "https://www.breezy-vcs.org/"
repository = "https://code.launchpad.net/breezyshim"
documentation = "https://www.breezy-vcs.org/doc/"
authors = [ "Martin Packman <gzlist@googlemail.com>", "Jelmer Vernooij <jelmer@jelmer.uk>",]
include = ["src/*.rs", "Cargo.toml", "COPYING.txt", "src/*/*.rs"]

[dependencies]
pyo3-filelike = ">=0.1"
tempfile = "3.6.0"
lazy_static = "1.4.0"
chrono = "0.4"
ctor = { version = "0.2.6", optional = true }
lazy-regex = "3.1.0"

[features]
default = ["debian", "auto-initialize"]
debian = ["dep:debversion"]
auto-initialize = ["dep:ctor"]

[dependencies.debversion]
version = ">=0.2"
optional = true
features = [ "python-debian",]

[dependencies.url]
version = "2"
features = [ "serde",]

[dependencies.serde]
version = "1"
features = [ "derive",]

[dependencies.pyo3]
workspace = true
features = [ "serde",]

[workspace.dependencies]
pyo3 = ">=0.20"

[dev-dependencies.pyo3]
workspace = true
