---
name: Rust

"on":
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13', '3.14']
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          sudo apt -y update
          sudo apt -y install bzr devscripts libapt-pkg-dev
        if: "matrix.os == 'ubuntu-latest'"
      - run: python -m pip install breezy launchpadlib
      - run: |
          python -m pip install \
            "git+https://github.com/breezy-team/breezy-debian" \
            python_apt@git+https://salsa.debian.org/apt-team/python-apt
        if: "matrix.os == 'ubuntu-latest' && matrix.python-version != '3.9'"
      - name: Build
        run: cargo build --verbose
        env:
          RUSTFLAGS: -Dwarnings
      - name: Run tests
        run: cargo test --verbose --features debian
        if: "matrix.os == 'ubuntu-latest'"
      - name: Run tests
        run: cargo test --verbose
        if: "matrix.os != 'macos-latest'"

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: |
          sudo apt -y update
          sudo apt -y install bzr devscripts libapt-pkg-dev
      - run: python -m pip install breezy launchpadlib
      - run: |
          python -m pip install \
            "git+https://github.com/breezy-team/breezy-debian" \
            python_apt@git+https://salsa.debian.org/apt-team/python-apt
      - name: Install cargo-hack and cargo-minimal-versions
        run: |
          cargo install cargo-hack
          cargo install cargo-minimal-versions
      - name: Test with minimal versions
        run: cargo minimal-versions test --verbose --features debian
        env:
          RUSTFLAGS: -Dwarnings
