name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo apt -y install bzr devscripts libapt-pkg-dev
      if: "matrix.os == 'ubuntu-latest'"
    - run: python -m pip install breezy launchpadlib
    - run: python -m pip install "bzr+lp:brz-debian" python_apt@git+https://salsa.debian.org/apt-team/python-apt.git@2.5.0
      if: "matrix.os == 'ubuntu-latest'"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features debian
      if: "matrix.os == 'ubuntu-latest'"
    - name: Run tests
      run: cargo test --verbose
      if: "matrix.os != 'macos-latest'"
